language: python
python:
- '2.7'

deploy:
  provider: pypi
  user: bgruening
  password:
    secure: "bNq0f4WjrWDm233CLz0H7RTyD4onfKQpm3AGyHhG+G7jKspVO/KbFHQX46Gs39LDg2S8ioYyYt/A2D7XSnQkuzZ9TzJ4jzVTVNJVkL1N373spFL4aE6okcGGDRGDJUcW4/DMvBk3J9Qhbzjn790uXjsV47poQL+X/wiEaHhn5g+jufEho7oYe1bdQ+I2kNqqmxH3oD6ZOOhGyVx/XKqM1SWwMGs/hQhAQMQbvqly4DOaogxMguHz0GAYsYxJ0E5racbXmlG1KXdMplx9DRxrLT9+USAruAgJ8+dzAvL/GURgudWeUM70AsNuIgFcwX5t3cc93K7Qo9nNAl8ldhJUr7O14l8Z9ejKRvGrfiO+i1gwPomWnoAy6Za/JtA0n//qgGKzYOQvKqanRIwJxRgTW5hfQ63+vc9k0vN5td9rxL8U2T3lkcjiarcODRxh1kD4KWw2/oxivAib/dwnrKF4USNOQK1dJ7PekQB01MZ4FGxYcGvVe2CAdjVG8U9UW5NelQq09C2KeQ0G9CmCKqDRsKPENRwV2z1b9IXujUYQ0ULUTzcqKPP8K5MmmcAZ4VpF6G9zVtWM9wkGoFX9L1PoEnST9uqFYCM4xIiBlWW/TnkDZL88rs43C1NIX11B91q4165gDnptBJvW3UK0YgRtmFkuMOexsFZen9ZlqCNBlVU="
  on:
    distributions: sdist bdist_wheel
    repo: bgruening/galaxy_ie_helpers
